/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeInput: typeof import('./src/components/code-input.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NInput: typeof import('naive-ui')['NInput']
    OButton: typeof import('onu-ui')['OButton']
    OCard: typeof import('onu-ui')['OCard']
    OInput: typeof import('onu-ui')['OInput']
  }
}
